### ISSUE TITLE
Fsys incorrectly uses filepath.FromSlash

### ISSUE THREAD

**Issue by kke** [k0sproject/rig#108]
The code has entries like:

```go
// Delete removes the named file or (empty) directory.
func (fsys *WinFsys) Delete(name string) error {
	if err := fsys.conn.Exec(fmt.Sprintf("del %s", ps.DoubleQuote(filepath.FromSlash(name)))); err != nil {
		return fmt.Errorf("%w: delete %s: %w", ErrCommandFailed, name, err)
	}
	return nil
}
```

The `filepath.FromSlash` returns a new path separated with the local separator:

```go
const (
	Separator     = os.PathSeparator
)

// FromSlash returns the result of replacing each slash ('/') character
// in path with a separator character. Multiple slashes are replaced
// by multiple separators.
func FromSlash(path string) string {
	if Separator == '/' {
		return path
	}
	return strings.ReplaceAll(path, "/", string(Separator))
}
```

This makes the local OS effect how remote paths are formatted, it should be the other way around.

**Comment by twz123** [comment]
Despite being weird, I think it doesn't matter that much in practice. Windows tests both backslashes as well as slashes as separator characters.

On the other hand: should there even be any path normalization in that function? Wouldn't callers pass in Windows style paths when connecting to windows machines anyways?
