### ISSUE TITLE
Problems while using SSH agent without key file

### ISSUE THREAD

**Issue by jadolg** [k0sproject/rig#161]
## Problem
When using a key that's only in the SSH agent, but other key(s) are present in the environment and agent, the configuration will only try to use these keys and ignore the ones in the agent.

## How to reproduce
- Create a new pair of keys and do NOT place them in the `.ssh` directory
- Deploy a host that can only be accessed with these keys
- Make sure there are other key(s) in the `.ssh` directory
- Add your newly created key to the ssh agent using `ssh-add`
- Try to use ssh (my specific problem is with k0sctl)

## Result: 
```
failed to connect: ssh dial: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

## Expected result
The connection uses the valid credentials that already are stored in the ssh agent.

## Observations
This is what I believe is the issue:
https://github.com/k0sproject/rig/blob/f0c372b43280c0e421768108f5d8a849088b94f7/ssh.go#L435-L441
In this code, `config.Auth = append(config.Auth, ssh.PublicKeys(signers...))` only happens if no other authentication method is found and this could lead to false positive auth.
I would like to have all the keys from the ssh agent available no matter if other keys are provided and maybe only restrict this if a specific key file is passed.

**Comment by kke** [comment]
> I would like to have all the keys from the ssh agent available no matter if other keys are provided and maybe only restrict this if a specific key file is passed.

Isn't this how it is currently? 🤔 If you give a key, only that key will be used, possibly after decrypting it using the agent. If you don't give a key, the default keys and any keys from the agent are tried.

I think there's big potential for confusion if you give a key but some other key magically ends up being used instead.

**Comment by jadolg** [comment]
This is how it is working now. If there's any key in .ssh, even if that key doesn't have access to the machine you are trying to connect to, it will just skip loading from the agent:
```mermaid
flowchart TD
    A[Config] --> B{Has a key configured}
    B -->|Yes| C[Use that key]
    B -->|No| D[Load keys from .ssh]
    D --> E{Are there any keys loaded}
    E --> |Yes| F[Use the keys loaded]
    E --> |No| G[Load the keys from the agent]
```
The desired scenario would be closer to 
```mermaid
flowchart TD
    A[Config] --> B{Has a key configured}
    B -->|Yes| C[Use that key]
    B -->|No| D[Load keys from .ssh]
    D --> G[Load the keys from the agent]
    G --> F[Use the keys loaded]
```

**Comment by jadolg** [comment]
Exactly, but the `use anything from the agent` part is not happening if default keys are found because in line no 435 `config.Auth` which gets filled with the default keys is checked instead of `c.AuthMethods` which are the explicitly configured keys

**Comment by kke** [comment]
Sounds sound.

**Comment by jadolg** [comment]
I opened a PR here https://github.com/k0sproject/rig/pull/162 but I'm struggling with the tests.
I have not managed to properly run the integration tests locally for the `main` branch.

**Comment by jadolg** [comment]
Closing since #162 got merged

**Comment by kke** [comment]
Btw, in the official client this behavior is controlled by the ssh config option "IdentitiesOnly".

When `yes`, only the specified identity files (keypaths) are used. If there are encrypted keys, the agent is checked if it has those available.

When `no` (the default), the specified identity files and all keys from the agent are tried. This may be problematic if the agent has a lot of keys and there's a limit on the server for login attempts. That is why the `IdentitiesOnly` option exists.

The default identity files are only tried if the user provided none.

But in the case of rig v0.x, the correct behavior should be to use the given keypath and its counterpart from the agent if it is encrypted and if no keypath was given, try all the defaults and everything from the agent.

**Comment by jadolg** [comment]
Just today I tried the latest k0sctl version and my problem is gone :smile:

**Comment by kke** [comment]
Someone else is saying the new version has introduced a problem in https://github.com/k0sproject/k0sctl/issues/674
