### ISSUE TITLE
Creating a Sudo() Client copy leads to nil pointer dereference

### ISSUE THREAD

**Issue by kaplan-michael** [k0sproject/rig#195]
I create the connections like this.  yet when I check with a debugger, the SudoClient seems to have nil as it's connection. I'm guessing it should either have a pointer to the original, or a copy of the original one? Is it a bug or am I doing something wrong?

``` golang
// setupHost configures and connects to a single host
func setupHost(hostConfig *HostConfig) (*Host, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	conn, err := createConnection(hostConfig)
	if err != nil {
		return nil, err
	}
	client, err := rig.NewClient(rig.WithConnection(conn), rig.WithLogger(logger.Slog))
	if err != nil {
		return nil, fmt.Errorf("failed to create rig client: %w", err)
	}

	err = client.Connect(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to connect: %w", err)
	}

	// Initialize sudo client at the same time
	sudoClient := client.Sudo()
	if sudoClient == nil {
		return nil, fmt.Errorf("failed to initialize sudo client")
	}

	return &Host{Client: client, Sudo: sudoClient, Vars: hostConfig.Vars, Fs: remotefs.NewFS(client)}, nil
}
```

**Comment by kaplan-michael** [comment]
From looking at it, it probably doesn't clone all required bits(doesn't init them) https://github.com/k0sproject/rig/blob/main/client.go#L252

so some internal Client bits end up being nil.

**Comment by kaplan-michael** [comment]
I think it is missing a call to the setup() method on the cloned client, hence the options don't get propagated. 
not sure what is the best place for it though.

**Comment by kke** [comment]
Hmm, setup does `c.Runner = c.options.GetRunner(c.connection)` which will overwrite the sudo Runner 🤔 

Doesn't the nil panic backtrace show what is nil?

The `Client` already memoizes the `sudoClone` when you do `h.Sudo()`, so keeping your own copy of it shouldn't be necessary. But it probably doesn't solve this nil problem.

**Comment by kaplan-michael** [comment]
I have tried to not keeping my copy and it behaved the same, so I started doing that so it's easier to debug. 

The backtrace wasn't very helpful(I'll try to share later), but from what I found I guess either the connection/the runner is nil. It doesn't get applied from the options to the Sudo client itself(and I assume something is trying to use that)

**Comment by kke** [comment]
I think @james-nesbitt solved it, PR incoming

**Comment by james-nesbitt** [comment]
https://github.com/k0sproject/rig/pull/199 makes sure that any client.Clone() has .setup() run before returning, which includes .Sudo()

**Comment by james-nesbitt** [comment]
oh. I didn't check the error as @kaplan-michael suggested. Let me update that.

**Comment by kaplan-michael** [comment]
Thanks @james-nesbitt. works good.
I do have a question in terms of sudo, do you plan/want to support sudo with a password?  probably injected through stdin?

**Comment by james-nesbitt** [comment]
for encrypted private keys I use ssh-agent and pre-load the key.

**Comment by kke** [comment]
> I do have a question in terms of sudo, do you plan/want to support sudo with a password? probably injected through stdin?

I'm undecided. I suppose it wouldn't be that hard to do, the biggest hurdle is when the sudo times out (could be after each command) and password is needed again, so the password would have to be kept in memory. Something like https://github.com/awnumar/memguard could help in doing it somewhat securely.

**Comment by kaplan-michael** [comment]
yeah, I do agree it would be nice to use memguard, but I feel like any password that are passed in will be through a flag or some kind of config, so I'm not sure if it justifies the effort to then try to keep it safe in memory? + It would be in memory on the system rig is running, which I guess in most cases is a single user personal system, so that mitigates it a bit more?
