### ISSUE TITLE
Support for dry runs?

### ISSUE THREAD

**Issue by kaplan-michael** [k0sproject/rig#205]
Do you plan/intend to have a support for something like a dry run? so that rig doesn't perform anything and just returns the command it is about to perform?

**Comment by kke** [comment]
In my opinion this should be done in the app that uses rig. It should possible to use `rigtest.MockRunner` and `NewClient(WithRunner(...))`.

I don't think dry-runs that would not run any commands would be very useful in most cases, non-destructive information gathering commands probably need to be used to decide which "destructive" actions to perform.

This was [done](https://github.com/search?q=repo%3Ak0sproject%2Fk0sctl%20p.wet&type=code) in k0sctl by screening every command and wrapping the ones that would make any changes.

**Comment by kaplan-michael** [comment]
Yeah, that makes sense, Thanks
